BEGIN;

-- ============================================
-- CREATE TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS "SanPhamNFT" (
    "Id"                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"                  TEXT        NOT NULL,
    "BatchNumber"           TEXT,
    "ManufactureDate"       TIMESTAMPTZ,
    "ExpiryDate"            TIMESTAMPTZ,
    "Description"           TEXT,
    "ImageUrl"              TEXT,
    "CertificateUrl"        TEXT,
    "Status"                TEXT        NOT NULL DEFAULT 'draft',
    "IpfsHash"              TEXT,
    "ManufacturerAddress"   TEXT,
    "DistributorAddress"    TEXT,
    "PharmacyAddress"       TEXT,
    "Gtin"                  TEXT,
    "Formulation"           TEXT,
    "TxHash"                TEXT,
    "CreatedAt"             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "YeuCauChuyen" (
    "Id"                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NftId"                 INTEGER     NOT NULL,
    "DistributorAddress"    TEXT        NOT NULL,
    "PharmacyAddress"       TEXT,
    "TransferNote"          TEXT,
    "Status"                TEXT        NOT NULL DEFAULT 'pending',
    "CreatedAt"             TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"             TIMESTAMPTZ,
    CONSTRAINT "FK_YeuCauChuyen_SanPhamNFT"
        FOREIGN KEY ("NftId") REFERENCES "SanPhamNFT"("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "MocDanhDau" (
    "Id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NftId"         INTEGER     NOT NULL,
    "Type"          TEXT        NOT NULL,
    "Description"   TEXT,
    "Location"      TEXT,
    "Timestamp"     TIMESTAMPTZ NOT NULL DEFAULT now(),
    "ActorAddress"  TEXT        NOT NULL,
    CONSTRAINT "FK_MocDanhDau_SanPhamNFT"
        FOREIGN KEY ("NftId") REFERENCES "SanPhamNFT"("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "SensorLogs" (
    "Id"                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NftId"                 INTEGER     NOT NULL,
    "DistributorAddress"    TEXT        NOT NULL,
    "Payload"               BYTEA       NOT NULL,
    "MimeType"              TEXT,
    "CreatedAt"             TIMESTAMPTZ NOT NULL DEFAULT now(),
    "ProcessedStatus"       TEXT        DEFAULT 'pending',
    "ProcessedAt"           TIMESTAMPTZ,
    "ProcessingError"       TEXT,
    CONSTRAINT "FK_SensorLogs_SanPhamNFT"
        FOREIGN KEY ("NftId") REFERENCES "SanPhamNFT"("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "NguoiDung" (
    "Id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Address"    TEXT        NOT NULL,
    "Role"       TEXT        NOT NULL,
    "AssignedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================
-- CREATE INDEXES
-- ============================================

CREATE INDEX IF NOT EXISTS "IX_SanPhamNFT_BatchNumber" ON "SanPhamNFT"("BatchNumber");
CREATE INDEX IF NOT EXISTS "IX_SanPhamNFT_Status" ON "SanPhamNFT"("Status");
CREATE INDEX IF NOT EXISTS "IX_YeuCauChuyen_NftId" ON "YeuCauChuyen"("NftId");
CREATE INDEX IF NOT EXISTS "IX_MocDanhDau_NftId" ON "MocDanhDau"("NftId");
CREATE INDEX IF NOT EXISTS "IX_SensorLogs_NftId" ON "SensorLogs"("NftId");
CREATE INDEX IF NOT EXISTS "IX_NguoiDung_Address" ON "NguoiDung"("Address");

-- ============================================
-- ALTER TABLES (Add columns if they don't exist)
-- ============================================

-- Note: These ALTER TABLE statements are only needed if the table already exists
-- and the columns are missing. If creating fresh tables, the columns are already
-- included in the CREATE TABLE statement above.

ALTER TABLE "SanPhamNFT" ADD COLUMN IF NOT EXISTS "Gtin" TEXT;
ALTER TABLE "SanPhamNFT" ADD COLUMN IF NOT EXISTS "Formulation" TEXT;
ALTER TABLE "SanPhamNFT" ADD COLUMN IF NOT EXISTS "TxHash" TEXT;

-- ============================================
-- MIGRATION HISTORY
-- ============================================

-- Create migration history table if it doesn't exist
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId"    TEXT        NOT NULL PRIMARY KEY,
    "ProductVersion" TEXT        NOT NULL
);

-- Insert migration record (only if not exists)
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251119031116_InitialCreate', '9.0.10')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;

